services:
  mysql-db:
    image: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=PQRxyz@07
    volumes:
      - ./mysql/startup_sql:/docker-entrypoint-initdb.d
      - mysql-ball:/var/lib/mysql

  backend:
    depends_on:
      - mysql-db
    build: 
      context: ./backend
    ports: 
      - 9090
    restart: on-failure
    
  proxy:
    image: nginx:alpine
    depends_on:
      - backend
    ports:
      - 4000:80  
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5173

volumes:
  mysql-ball:
